### ISSUE TITLE
下拉出现的那三条线每次出现的都不一样。。而且没有在最中间

### ISSUE THREAD

**Issue by liuyatao** [cloay/CRefreshLayout#1]

**Comment by cloay** [comment]
这个项目还没有正式完成，请等待，抱歉！

**Comment by liuyatao** [comment]
很期待！ 可以学习一下！

------------------ 原始邮件 ------------------
发件人: "Weimin Shang"notifications@github.com; 
发送时间: 2014年11月12日(星期三) 上午10:35
收件人: "cloay/CRefreshLayout"CRefreshLayout@noreply.github.com; 
抄送: "刘亚涛 "739697044@qq.com; 
主题: Re: [CRefreshLayout] 下拉出现的那三条线每次出现的都不一样。。而且没有在最中间 (#1)

这个项目还没有正式完成，请等待，抱歉！
