### ISSUE TITLE
replace loading text 

### ISSUE THREAD

**Issue by sikandercb** [cloay/CRefreshLayout#2]
an you add this text "bcliuketp"   or give me code ponits code of this ...?

**Comment by cloay** [comment]
Add your text points to the init method in the CRefreshView.
There is a better lib <a href='https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh'>android-Ultra-Pull-To-Refresh</a> , you can have a try.

**Comment by sikandercb** [comment]
thanks @cloay
